LANGUAGES = {
    "en": "🇬🇧 English",
    "pt": "🇧🇷 Português",
    "de": "🇩🇪 Deutsch",
    "es": "🇪🇸 Español",
    "pl": "🇵🇱 Polski",
    "ga": "🇮🇪 Gaeilge",
}

MESSAGES = {
    "en": {
        "ask_language": "🌍 Language - Lingua - Sprache",
        "ask_age": "🔞 Are you 18 years or older?",
        "yes": "✅ Yes",
        "no": "❌ No",
        "too_young": "🚫 You must be 18 years old to use this service.",
        "welcome": "🎉 Welcome to BacchusBot!\n\n✨ Our agency helps you save time so you can enjoy life.",
        "join_group": "🔗 Join our community:",
        "work_with_us": "💼 Work with us",
        "contact_us": "📞 Contact us",
        "subscribe": "📩 Subscribe",
    },
    "pt": {
        "ask_language": "🌍 Language - Lingua - Sprache",
        "ask_age": "🔞 Você tem 18 anos ou mais?",
        "yes": "✅ Sim",
        "no": "❌ Não",
        "too_young": "🚫 Você deve ter 18 anos para usar este serviço.",
        "welcome": "🎉 Bem-vindo ao BacchusBot!\n\n✨ Nossa agência ajuda você a economizar tempo para que possa aproveitar a vida.",
        "join_group": "🔗 Entre na nossa comunidade:",
        "work_with_us": "💼 Trabalhe conosco",
        "contact_us": "📞 Entre em contato",
        "subscribe": "📩 Inscreva-se",
    },
    "de": {
        "ask_language": "🌍 Language - Lingua - Sprache",
        "ask_age": "🔞 Bist du 18 Jahre oder älter?",
        "yes": "✅ Ja",
        "no": "❌ Nein",
        "too_young": "🚫 Du musst 18 Jahre alt sein, um diesen Dienst zu nutzen.",
        "welcome": "🎉 Willkommen bei BacchusBot!\n\n✨ Unsere Agentur hilft Ihnen, Zeit zu sparen, damit Sie Ihr Leben genießen können.",
        "join_group": "🔗 Tritt unserer Community bei:",
        "work_with_us": "💼 Arbeiten Sie mit uns",
        "contact_us": "📞 Kontaktieren Sie uns",
        "subscribe": "📩 Abonnieren",
    },
    "es": {
        "ask_language": "🌍 Language - Lingua - Sprache",
        "ask_age": "🔞 ¿Tienes 18 años o más?",
        "yes": "✅ Sí",
        "no": "❌ No",
        "too_young": "🚫 Debes tener 18 años para usar este servicio.",
        "welcome": "🎉 ¡Bienvenido a BacchusBot!\n\n✨ Nuestra agencia te ayuda a ahorrar tiempo para que puedas disfrutar la vida.",
        "join_group": "🔗 Únete a nuestra comunidad:",
        "work_with_us": "💼 Trabaja con nosotros",
        "contact_us": "📞 Contáctanos",
        "subscribe": "📩 Suscribirse",
    },
    "pl": {
        "ask_language": "🌍 Language - Lingua - Sprache",
        "ask_age": "🔞 Czy masz 18 lat lub więcej?",
        "yes": "✅ Tak",
        "no": "❌ Nie",
        "too_young": "🚫 Musisz mieć 18 lat, aby korzystać z tej usługi.",
        "welcome": "🎉 Witamy w BacchusBot!\n\n✨ Nasza agencja pomaga Ci oszczędzać czas, abyś mógł cieszyć się życiem.",
        "join_group": "🔗 Dołącz do naszej społeczności:",
        "work_with_us": "💼 Pracuj z nami",
        "contact_us": "📞 Skontaktuj się z nami",
        "subscribe": "📩 Subskrybuj",
    },
    "ga": {
        "ask_language": "🌍 Language - Lingua - Sprache",
        "ask_age": "🔞 An bhfuil tú 18 mbliana nó níos sine?",
        "yes": "✅ Tá",
        "no": "❌ Níl",
        "too_young": "🚫 Caithfidh tú a bheith 18 mbliana d’aois chun an tseirbhís seo a úsáid.",
        "welcome": "🎉 Fáilte go BacchusBot!\n\n✨ Cabhraíonn ár ngníomhaireacht leat am a shábháil ionas gur féidir leat taitneamh a bhaint as an saol.",
        "join_group": "🔗 Bígí linn sa phobal:",
        "work_with_us": "💼 Oibrigh linn",
        "contact_us": "📞 Déan teagmháil linn",
        "subscribe": "📩 Liostáil",
    },
}
